// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKoC9ivUN2tgMV_AQr5rTAkeZ_nk-GrV4',
    appId: '1:942655850840:web:7386fe8c73dd83201efd2d',
    messagingSenderId: '942655850840',
    projectId: 'uas-project-2eecb',
    authDomain: 'uas-project-2eecb.firebaseapp.com',
    storageBucket: 'uas-project-2eecb.firebasestorage.app',
    measurementId: 'G-F6R8VLXV6W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHKb3bQrdaWqeiBs4jl6sCbgm_Fyf38PU',
    appId: '1:942655850840:android:6a0bdba6fda2a8f01efd2d',
    messagingSenderId: '942655850840',
    projectId: 'uas-project-2eecb',
    storageBucket: 'uas-project-2eecb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUcsZ0ucktOfcVz0lXxEaaBoS6qmP6OEw',
    appId: '1:942655850840:ios:6dc44d7e2c56e39b1efd2d',
    messagingSenderId: '942655850840',
    projectId: 'uas-project-2eecb',
    storageBucket: 'uas-project-2eecb.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationUas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUcsZ0ucktOfcVz0lXxEaaBoS6qmP6OEw',
    appId: '1:942655850840:ios:6dc44d7e2c56e39b1efd2d',
    messagingSenderId: '942655850840',
    projectId: 'uas-project-2eecb',
    storageBucket: 'uas-project-2eecb.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationUas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKoC9ivUN2tgMV_AQr5rTAkeZ_nk-GrV4',
    appId: '1:942655850840:web:ab10d3ddb51274cc1efd2d',
    messagingSenderId: '942655850840',
    projectId: 'uas-project-2eecb',
    authDomain: 'uas-project-2eecb.firebaseapp.com',
    storageBucket: 'uas-project-2eecb.firebasestorage.app',
    measurementId: 'G-VRJHZNPKH2',
  );

}